name: Update YouTube Video

on:
  push:
  schedule:
    - cron: "0 */6 * * *" # This will run every 6 hours. Adjust as needed.

jobs:
  update_video:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Make sure this matches your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run the script
        run: python ./main.py
        env:
          TOKEN_PICKLE: ${{ secrets.TOKEN_PICKLE }}
          CLIENT_CONFIG_JSON: ${{ secrets.CLIENT_CONFIG_JSON }}
